# Generated by Django 3.1 on 2020-08-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0002_auto_20200828_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='full_path',
            new_name='description',
        ),
    ]
